site_name: Notifications+ Documentation
site_url: https://notifications-documentation.readthedocs.io/en/latest/
nav:
    - Getting Started: index.md
    - User Guide:
      - Profile Menu: user-guide/profile-menu.md
      - Datatable: user-guide/datatable.md
      - Datatable Actions: user-guide/datatable-actions.md
theme:
  name: readthedocs