site_name: Notifications+ Documentation
site_url: https://notifications-documentation.readthedocs.io/en/latest/
nav:
    - Getting Started: index.md
    - User Guide:
      - Interface: user-guide/interface.md
      - Profile Menu: user-guide/profile-menu.md
theme:
  name: readthedocs